version: '3'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '5000:5000'
    volumes:
      - .:/usr/src/app
    depends_on:
      - mongodb
    environment:
      NODE_ENV: development
      PORT: 5000
      DB_URL: mongodb://mongodb:27017/crystalized-hair
      JWT_SECRET: g3tcryst@liz3d! #TODO: kill this
  mongodb:
    image: mongo:4
    restart: always
    ports:
      - '27017:27017'
    volumes:
      - '.:/data'
