version: '3'

services:
  client:
    build:
      context: ./crystalized-beauty-web
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    volumes:
      - ./crystalized-beauty-web:/usr/src/app
    depends_on:
      - api
  api:
    build:
      context: ./crystalized-beauty-api
      dockerfile: Dockerfile
    ports:
      - '5000:5000'
    volumes:
      - ./crystalized-beauty-api:/usr/src/app
    depends_on:
      - mongodb
    environment:
      NODE_ENV: development
      PORT: 5000
      DB_URL: mongodb://mongodb:27017/crystalized-hair
      JWT_SECRET: g3tcryst@liz3d! #TODO: kill this
  mongodb:
    image: mongo:4
    ports:
      - '27017:27017'
    restart: unless-stopped
